"""
End-to-end tests on real RCSR topologies from the committed fixture.

The fixture (tests/data/topologies_fixture.json) holds pcu, srs and dia,
generated by scripts/make_test_fixture.py from verbatim RCSR CGD
entries. These tests exercise the full pipeline - JSON loading, slot
compatibility, alignment, cell optimization - without the full
topology database.
"""

import os

import numpy as np
import pytest

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "data", "topologies_fixture.json"
)


@pytest.fixture(scope="module")
def mofgen():
    """Autografs with the default SBU library and fixture topologies."""
    from autografs import Autografs

    return Autografs(topofile=FIXTURE_PATH)


class TestFixtureLibrary:
    """The fixture loads with correct crystallographic content."""

    def test_all_nets_present(self, mofgen):
        assert sorted(mofgen.topologies) == ["acs", "dia", "hcb", "pcu", "sql", "srs"]

    def test_layer_nets_flagged_2d(self, mofgen):
        for net in ("hcb", "sql"):
            assert mofgen.topologies[net].is_2d
        for net in ("pcu", "srs", "dia", "acs"):
            assert not mofgen.topologies[net].is_2d

    @pytest.mark.parametrize(
        "net, n_slots, node_pg, node_conn, n_nodes, sg",
        [
            ("pcu", 4, "Oh", 6, 1, 221),
            ("srs", 20, "D3h", 3, 8, 214),
            ("dia", 24, "Td", 4, 8, 227),
            # acs nodes are 6-c "trigonal prisms", but at the RCSR
            # maximum-symmetry embedding ratio the star's geometric
            # symmetry is exactly Td (cosines 1/3, 0, -2/3) - higher
            # than the D3h site symmetry. The label reflects the star.
            ("acs", 8, "Td", 6, 2, 194),
            # 2D nets store the plane-group number (17 = p6mm, 11 = p4mm)
            ("hcb", 5, "D3h", 3, 2, 17),
            ("sql", 3, "D4h", 4, 1, 11),
        ],
    )
    def test_net_crystallography(
        self, mofgen, net, n_slots, node_pg, node_conn, n_nodes, sg
    ):
        """Node slots carry the textbook point group and multiplicity."""
        topology = mofgen.topologies[net]
        assert len(topology) == n_slots
        assert topology.spacegroup_number == sg
        node_types = {
            key: indices
            for key, indices in topology.mappings.items()
            if len(key.atoms.indices_from_symbol("X")) == node_conn
        }
        assert len(node_types) == 1
        key, indices = node_types.popitem()
        assert key.pointgroup == node_pg
        assert len(indices) == n_nodes

    def test_equivalence_classes_stored(self, mofgen):
        for topology in mofgen.topologies.values():
            for slot in topology.slots:
                assert slot.equivalence_class is not None

    def test_listing_compatible_units(self, mofgen):
        """Real SBUs from the default library match the pcu slots."""
        available = mofgen.list_building_units(sieve="pcu")
        by_conn = {
            len(k.atoms.indices_from_symbol("X")): v for k, v in available.items()
        }
        assert "Zn_mof5_octahedral" in by_conn[6]
        assert "Benzene_linear" in by_conn[2]


class TestGoldenBuilds:
    """Golden regression: known MOFs built from real topologies."""

    @staticmethod
    def _mappings_by_connectivity(topology, choices):
        """Map each slot type to an SBU name by dummy count."""
        mappings = {}
        for key in topology.mappings:
            conn = len(key.atoms.indices_from_symbol("X"))
            mappings[key] = choices[conn]
        return mappings

    def test_mof5_like_build(self, mofgen):
        """pcu + Zn4O + benzene = the MOF-5 prototype.

        Golden regression for the directional alignment core: the
        bond-length pair objective must find the cubic MOF-5 cell
        (experimental a = 12.9 A; the old dummy-coincidence objective
        landed at 12.77 by hard-coding 1.4 A inter-fragment bonds).
        """
        topology = mofgen.topologies["pcu"]
        mappings = self._mappings_by_connectivity(
            topology, {6: "Zn_mof5_octahedral", 2: "Benzene_linear"}
        )
        framework = mofgen.build(
            topology, mappings=mappings, refine_cell=True, max_rmsd=0.5
        )

        # expected atom count: sum over slots of (atoms - dummies)
        expected = 0
        for key, indices in topology.mappings.items():
            sbu = mofgen.sbu[mappings[key]]
            n_real = len(sbu.atoms) - len(sbu.atoms.indices_from_symbol("X"))
            expected += n_real * len(indices)
        assert len(framework) == expected

        # the optimized cell of this cubic net must be cubic and sized
        # like MOF-5
        abc = np.linalg.norm(framework.cell, axis=1)
        np.testing.assert_allclose(abc, abc[0], rtol=1e-3)
        assert 12.8 < abc[0] < 13.0
        # every atom bonded: no isolated nodes
        degrees = [d for _, d in framework.graph.degree()]
        assert min(degrees) >= 1
        # inter-fragment (tag-paired) bonds sit at the Cordero C-C
        # bond length, not at whatever the dummy placement implies
        structure = framework.structure
        tags = structure.site_properties["tags"]
        by_tag = {}
        for i, tag in enumerate(tags):
            if tag > 0:
                by_tag.setdefault(tag, []).append(i)
        assert by_tag, "no inter-fragment bonds found"
        for pair in by_tag.values():
            assert len(pair) == 2
            distance = structure.get_distance(*pair)
            assert distance == pytest.approx(1.46, abs=0.02)

    def test_mof5_build_is_deterministic(self, mofgen):
        topology = mofgen.topologies["pcu"]
        mappings = self._mappings_by_connectivity(
            topology, {6: "Zn_mof5_octahedral", 2: "Benzene_linear"}
        )

        def coords():
            framework = mofgen.build(
                topology, mappings=dict(mappings), refine_cell=False
            )
            return framework.cart_coords

        np.testing.assert_array_almost_equal(coords(), coords(), decimal=10)

    def test_dia_build(self, mofgen):
        """dia + tetrahedral SBU + linear linker: cubic optimized cell."""
        topology = mofgen.topologies["dia"]
        available = mofgen.list_building_units(sieve="dia")
        by_conn = {
            len(k.atoms.indices_from_symbol("X")): (k, v) for k, v in available.items()
        }
        assert 4 in by_conn, "no tetrahedral SBU matched dia nodes"
        key4, sbus4 = by_conn[4]
        key2, sbus2 = by_conn[2]
        framework = mofgen.build(
            topology,
            mappings={key4: sorted(sbus4)[0], key2: "Benzene_linear"},
            refine_cell=True,
            max_rmsd=0.5,
        )
        assert len(framework) > 0
        abc = np.linalg.norm(framework.cell, axis=1)
        np.testing.assert_allclose(abc, abc[0], rtol=1e-3)
        assert abc[0] > 10.0

    def test_build_all_with_sampling(self, mofgen):
        """build_all streams combinations and caps them reproducibly."""
        kwargs = dict(
            topology_subset=["pcu"],
            max_per_topology=3,
            seed=42,
            refine_cell=False,
        )
        first = mofgen.build_all(**kwargs)
        second = mofgen.build_all(**kwargs)

        assert 0 < len(first) <= 3
        # a fixed seed reproduces the same sampled combinations
        assert [fw.formula for fw in first] == [fw.formula for fw in second]
        # a different seed picks a different sample (pcu has 58 combos)
        third = mofgen.build_all(**{**kwargs, "seed": 7})
        assert len(third) <= 3

    @pytest.mark.slow
    def test_build_all_parallel_matches_serial(self, mofgen):
        """n_jobs > 1 produces the same frameworks as serial."""
        kwargs = dict(
            topology_subset=["pcu"],
            max_per_topology=3,
            seed=11,
            refine_cell=False,
        )
        serial = mofgen.build_all(n_jobs=1, **kwargs)
        parallel = mofgen.build_all(n_jobs=2, **kwargs)
        assert [fw.formula for fw in serial] == [fw.formula for fw in parallel]

    def test_deduplicate_helper_drops_equivalent_structures(self, mofgen):
        """Equivalent crystals collapse to their first representative."""
        from autografs.builder import _deduplicate_frameworks

        topology = mofgen.topologies["pcu"]
        mappings = {}
        for key in topology.mappings:
            conn = len(key.atoms.indices_from_symbol("X"))
            mappings[key] = {6: "Zn_mof5_octahedral", 2: "Benzene_linear"}[conn]
        mof = mofgen.build(topology, mappings=mappings, refine_cell=False)
        twin = mofgen.build(topology, mappings=mappings, refine_cell=False)
        hcb = mofgen.topologies["hcb"]
        layer_mappings = {}
        for key in hcb.mappings:
            conn = len(key.atoms.indices_from_symbol("X"))
            layer_mappings[key] = {3: "Boroxine_triangle", 2: "Benzene_linear"}[conn]
        layer = mofgen.build(hcb, mappings=layer_mappings, max_rmsd=0.5)

        kept = _deduplicate_frameworks([mof, twin, layer])
        assert kept == [mof, layer]  # first occurrence wins, order stable

    def test_build_all_deduplicate_flag(self, mofgen):
        kwargs = dict(
            topology_subset=["pcu"],
            max_per_topology=3,
            seed=42,
            refine_cell=False,
        )
        raw = mofgen.build_all(**kwargs)
        deduped = mofgen.build_all(deduplicate=True, **kwargs)
        assert 0 < len(deduped) <= len(raw)
        # the deduplicated list is a stable subsequence of the raw one
        it = iter(fw.formula for fw in raw)
        assert all(any(f == g for g in it) for f in (fw.formula for fw in deduped))

    def test_cof1_like_build(self, mofgen):
        """hcb + boroxine + benzene = the COF-1 prototype layer.

        Golden regression for the 2D pipeline: plane-group expansion,
        layer-mode cell optimization (a = b, gamma = 120 by
        construction, c exactly frozen at the slab padding), and
        stacking. The layer must render a bonded honeycomb, not a
        setting-mangled net.
        """
        topology = mofgen.topologies["hcb"]
        assert topology.is_2d
        pad_c = topology.cell.c
        mappings = self._mappings_by_connectivity(
            topology, {3: "Boroxine_triangle", 2: "Benzene_linear"}
        )
        framework = mofgen.build(
            topology, mappings=mappings, refine_cell=True, max_rmsd=0.5
        )

        # expected atom count: sum over slots of (atoms - dummies)
        expected = 0
        for key, indices in topology.mappings.items():
            sbu = mofgen.sbu[mappings[key]]
            n_real = len(sbu.atoms) - len(sbu.atoms.indices_from_symbol("X"))
            expected += n_real * len(indices)
        assert len(framework) == expected

        # layer-mode parametrization: hexagonal to machine precision
        # (the 1-ulp noise comes from Lattice recomputing parameters
        # from the matrix, not from the optimizer), c untouched by
        # refine_cell=True
        lattice = framework.lattice
        assert abs(lattice.a - lattice.b) < 1e-12
        assert abs(lattice.gamma - 120.0) < 1e-12
        assert abs(lattice.alpha - 90.0) < 1e-12
        assert abs(lattice.beta - 90.0) < 1e-12
        assert lattice.c == pad_c
        # COF-1 experimental a = 15.0 A. The bond-length pair objective
        # gives ~14.7 with B-C pinned at the Cordero 1.57 A (the old
        # dummy-coincidence objective overshot to 15.6 because the
        # boroxine dummy placement implied a 1.9 A B-C bond); the
        # remaining gap is SBU-internal geometry, not the cell fit
        assert 14.3 < lattice.a < 15.1

        # layer planarity: everything in a thin window around z = 0.
        # The default Boroxine_triangle SBU is slightly pyramidal
        # (its O/B/X atoms sit up to ~0.5 A off its arm plane), so the
        # layer has real thickness; the linkers must stay exactly flat
        z = framework.cart_coords[:, 2]
        assert np.abs(z).max() < 1.0
        carbons = [s == "C" for s in framework.symbols]
        assert np.abs(z[carbons]).max() < 1e-9

        # honeycomb connectivity: one bonded component, no dangling SBU
        import networkx

        assert networkx.is_connected(framework.graph)
        degrees = [d for _, d in framework.graph.degree()]
        assert min(degrees) >= 1

        # stacking replaces the padding with a real interlayer spacing
        aa = framework.stack(mode="AA", interlayer=3.35)
        assert len(aa) == len(framework)
        assert abs(aa.lattice.c - 3.35) < 1e-9
        ab = framework.stack(mode="AB", interlayer=3.35)
        assert len(ab) == 2 * len(framework)
        assert abs(ab.lattice.c - 6.70) < 1e-9

    def test_sql_build_stays_square(self, mofgen):
        """sql (p4mm): square layer cell with frozen c."""
        topology = mofgen.topologies["sql"]
        available = mofgen.list_building_units(sieve="sql")
        by_conn = {
            len(k.atoms.indices_from_symbol("X")): (k, v) for k, v in available.items()
        }
        assert 4 in by_conn, "no square-planar SBU matched sql nodes"
        key4, sbus4 = by_conn[4]
        key2, _ = by_conn[2]
        framework = mofgen.build(
            topology,
            mappings={key4: sorted(sbus4)[0], key2: "Benzene_linear"},
            refine_cell=True,
        )
        lattice = framework.lattice
        assert abs(lattice.a - lattice.b) < 1e-12
        assert abs(lattice.gamma - 90.0) < 1e-12
        assert lattice.c == topology.cell.c

    def test_acs_build_stays_hexagonal(self, mofgen):
        """acs (P6_3/mmc): the optimized cell keeps hexagonal symmetry.

        The crystal-system parametrization exposes only (a, c) for
        spacegroup 194, so a = b and gamma = 120 by construction.
        """
        topology = mofgen.topologies["acs"]
        available = mofgen.list_building_units(sieve="acs")
        by_conn = {
            len(k.atoms.indices_from_symbol("X")): (k, v) for k, v in available.items()
        }
        assert 6 in by_conn, "no 6-c SBU matched acs nodes"
        key6, sbus6 = by_conn[6]
        key2, _ = by_conn[2]
        framework = mofgen.build(
            topology,
            mappings={key6: sorted(sbus6)[0], key2: "Benzene_linear"},
            refine_cell=True,
        )
        lattice = framework.lattice
        assert abs(lattice.a - lattice.b) < 1e-6
        assert abs(lattice.gamma - 120.0) < 1e-6
        assert abs(lattice.alpha - 90.0) < 1e-6
