"""
End-to-end tests on real RCSR topologies from the committed fixture.

The fixture (tests/data/topologies_fixture.json) holds pcu, srs and dia,
generated by scripts/make_test_fixture.py from verbatim RCSR CGD
entries. These tests exercise the full pipeline - JSON loading, slot
compatibility, alignment, cell optimization - without the full
topology database.
"""

import os

import numpy as np
import pytest

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "data", "topologies_fixture.json"
)


@pytest.fixture(scope="module")
def mofgen():
    """Autografs with the default SBU library and fixture topologies."""
    from autografs import Autografs

    return Autografs(topofile=FIXTURE_PATH)


class TestFixtureLibrary:
    """The fixture loads with correct crystallographic content."""

    def test_all_nets_present(self, mofgen):
        assert sorted(mofgen.topologies) == ["dia", "pcu", "srs"]

    @pytest.mark.parametrize(
        "net, n_slots, node_pg, node_conn, n_nodes, sg",
        [
            ("pcu", 4, "Oh", 6, 1, 221),
            ("srs", 20, "D3h", 3, 8, 214),
            ("dia", 24, "Td", 4, 8, 227),
        ],
    )
    def test_net_crystallography(
        self, mofgen, net, n_slots, node_pg, node_conn, n_nodes, sg
    ):
        """Node slots carry the textbook point group and multiplicity."""
        topology = mofgen.topologies[net]
        assert len(topology) == n_slots
        assert topology.spacegroup_number == sg
        node_types = {
            key: indices
            for key, indices in topology.mappings.items()
            if len(key.atoms.indices_from_symbol("X")) == node_conn
        }
        assert len(node_types) == 1
        key, indices = node_types.popitem()
        assert key.pointgroup == node_pg
        assert len(indices) == n_nodes

    def test_equivalence_classes_stored(self, mofgen):
        for topology in mofgen.topologies.values():
            for slot in topology.slots:
                assert slot.equivalence_class is not None

    def test_listing_compatible_units(self, mofgen):
        """Real SBUs from the default library match the pcu slots."""
        available = mofgen.list_building_units(sieve="pcu")
        by_conn = {
            len(k.atoms.indices_from_symbol("X")): v for k, v in available.items()
        }
        assert "Zn_mof5_octahedral" in by_conn[6]
        assert "Benzene_linear" in by_conn[2]


class TestGoldenBuilds:
    """Golden regression: known MOFs built from real topologies."""

    @staticmethod
    def _mappings_by_connectivity(topology, choices):
        """Map each slot type to an SBU name by dummy count."""
        mappings = {}
        for key in topology.mappings:
            conn = len(key.atoms.indices_from_symbol("X"))
            mappings[key] = choices[conn]
        return mappings

    def test_mof5_like_build(self, mofgen):
        """pcu + Zn4O + benzene = the MOF-5 prototype.

        Golden regression for the directional alignment core: the
        pair-coincidence objective must find the cubic MOF-5 cell
        (experimental a = 12.9 A; the dummy-overlap convention of the
        SBU library gives ~12.8).
        """
        topology = mofgen.topologies["pcu"]
        mappings = self._mappings_by_connectivity(
            topology, {6: "Zn_mof5_octahedral", 2: "Benzene_linear"}
        )
        graph = mofgen.build(
            topology, mappings=mappings, refine_cell=True, max_rmsd=0.5
        )

        # expected atom count: sum over slots of (atoms - dummies)
        expected = 0
        for key, indices in topology.mappings.items():
            sbu = mofgen.sbu[mappings[key]]
            n_real = len(sbu.atoms) - len(sbu.atoms.indices_from_symbol("X"))
            expected += n_real * len(indices)
        assert graph.number_of_nodes() == expected

        # the optimized cell of this cubic net must be cubic and sized
        # like MOF-5
        cell = graph.graph["cell"]
        abc = np.linalg.norm(cell, axis=1)
        np.testing.assert_allclose(abc, abc[0], rtol=1e-3)
        assert 12.0 < abc[0] < 13.5
        # every atom bonded: no isolated nodes
        degrees = [d for _, d in graph.degree()]
        assert min(degrees) >= 1

    def test_mof5_build_is_deterministic(self, mofgen):
        topology = mofgen.topologies["pcu"]
        mappings = self._mappings_by_connectivity(
            topology, {6: "Zn_mof5_octahedral", 2: "Benzene_linear"}
        )

        def coords():
            graph = mofgen.build(
                topology, mappings=dict(mappings), refine_cell=False
            )
            return np.array(
                [graph.nodes[n]["coord"] for n in sorted(graph.nodes())]
            )

        np.testing.assert_array_almost_equal(coords(), coords(), decimal=10)

    def test_dia_build(self, mofgen):
        """dia + tetrahedral SBU + linear linker: cubic optimized cell."""
        topology = mofgen.topologies["dia"]
        available = mofgen.list_building_units(sieve="dia")
        by_conn = {
            len(k.atoms.indices_from_symbol("X")): (k, v)
            for k, v in available.items()
        }
        assert 4 in by_conn, "no tetrahedral SBU matched dia nodes"
        key4, sbus4 = by_conn[4]
        key2, sbus2 = by_conn[2]
        graph = mofgen.build(
            topology,
            mappings={key4: sorted(sbus4)[0], key2: "Benzene_linear"},
            refine_cell=True,
            max_rmsd=0.5,
        )
        assert graph.number_of_nodes() > 0
        abc = np.linalg.norm(graph.graph["cell"], axis=1)
        np.testing.assert_allclose(abc, abc[0], rtol=1e-3)
        assert abc[0] > 10.0
