"""
Tests for the bundled PORMAKE building-block library.

The library (src/autografs/data/pormake.xyz, MIT-licensed, see
PORMAKE_LICENSE.md) is generated by scripts/import_pormake_bbs.py and
loaded alongside the curated defaults.
"""

import os

import numpy as np
import pytest

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "data", "topologies_fixture.json"
)


@pytest.fixture(scope="module")
def mofgen():
    from autografs import Autografs

    return Autografs(topofile=FIXTURE_PATH)


class TestLibraryLoading:
    def test_pormake_sbus_present(self, mofgen):
        pormake = [n for n in mofgen.sbu if n.startswith("pormake_")]
        assert len(pormake) > 800
        # the curated defaults are still there
        assert "Zn_mof5_octahedral" in mofgen.sbu
        assert "Benzene_linear" in mofgen.sbu

    def test_connectivity_gaps_filled(self, mofgen):
        """The import's point: connectivities the defaults lack."""
        by_conn = {}
        for name, sbu in mofgen.sbu.items():
            if name.startswith("pormake_"):
                conn = len(sbu.atoms.indices_from_symbol("X"))
                by_conn.setdefault(conn, []).append(name)
        for needed in (7, 9, 10, 24):
            assert needed in by_conn, f"no {needed}-connected SBU imported"

    def test_dummies_have_nearby_anchors(self, mofgen):
        """Every connection point sits within bonding range of a real
        atom - the anchor the bond-length objective relies on."""
        rng = np.random.default_rng(3)
        pormake = sorted(n for n in mofgen.sbu if n.startswith("pormake_"))
        for name in rng.choice(pormake, size=25, replace=False):
            sbu = mofgen.sbu[name]
            coords = np.asarray(sbu.atoms.cart_coords)
            real = [i for i, s in enumerate(sbu.atoms) if s.specie.symbol != "X"]
            for i in sbu.atoms.indices_from_symbol("X"):
                nearest = np.linalg.norm(coords[real] - coords[i], axis=1).min()
                assert nearest < 2.0, f"{name}: dangling connection point"


class TestPormakeBuilds:
    def test_pcu_build_with_pormake_sbus(self, mofgen):
        """A known-good all-PORMAKE combination builds a clean pcu MOF."""
        topology = mofgen.topologies["pcu"]
        slot6 = next(
            k for k in topology.mappings if len(k.atoms.indices_from_symbol("X")) == 6
        )
        slot2 = next(
            k for k in topology.mappings if len(k.atoms.indices_from_symbol("X")) == 2
        )
        framework = mofgen.build(
            topology,
            mappings={slot6: "pormake_N106", slot2: "pormake_E10"},
            max_rmsd=0.4,
            min_distance=0.9,
        )
        abc = np.array(framework.lattice.abc)
        np.testing.assert_allclose(abc, abc[0], rtol=1e-3)
        assert framework.min_contact() > 0.9

    def test_pormake_candidates_in_sieve(self, mofgen):
        options = mofgen.list_building_units(sieve="pcu", verbose=False)
        names = [n for values in options.values() for n in values]
        assert any(n.startswith("pormake_") for n in names)
